### ISSUE TITLE
Request to release raw video data or high-quality sampled images

### ISSUE THREAD

**Issue by zcq15** [yuniw18/Joint_360depth#2]
Thanks for your work! Could you please release the raw video data or high-quality sample images? There are many artifacts in existing JPG images due to compression encoding.

**Comment by yuniw18** [comment]
Sorry for the delayed upload. 
Because raw data is huge, we are preparing with some other datasets together.
We expect it to be uploaded within a month.
Thank you.

**Comment by yuniw18** [comment]
Hi,

We just upload the dataset with higher resolutions and more various scenes.
 Meanwhile, raw video data (before stitching)  is not provided because the file size is too large and raw video data requires each own stitching software to be post-processed according to the camera modules . 

If you have any further inquiries, please re-open this issue.

Thank you.
